[template]
src = "mongod.conf.tmpl"
dest = "/opt/app/current/conf/mongodb/mongod.conf"
keys = [
  "/env/maxConns",
  "/env/oplogSize",
  "/env/port",
  "/env/rsName",
]
reload_cmd = "appctl changeMongodbCfg"