---

- name: apt install required packages
  apt:
    update_cache: yes
    name: [ 'vim', 'xfsprogs', 'python2.7-dev', 'python-pip', 'htop', 'lsof', 'bwm-ng', 'python-simplejson']
    state: present

- group:
    name: mongodb
    state: present

- user:
    name: mongodb
    group: mongodb
    createhome: no
    state: present

- name: set local
  locale_gen: name=zh_CN.UTF-8 state=present

- file: path={{item}} state=directory mode=0755
  with_items:
    - /opt
    - /root/.pip/
    - /opt/app/conf/caddy

- name: put pip conf
  copy: src=pip.conf dest=/root/.pip/pip.conf

- name: put requirements
  copy: src=requirements.txt dest=/tmp/requirements.txt

- name: pip install requirements
  pip: requirements=/tmp/requirements.txt executable=pip

- name: put bashrc
  copy: src=bashrc.sh dest=/root/.bashrc

- get_url:
    url: http://downloads.mongodb.org/linux/{{item.mongodb_version}}.tgz
    dest: /tmp/{{item.mongodb_version}}.tgz
    checksum: sha256:{{item.mongodb_sha}}
  with_items:
    - {mongodb_version: "{{mongodb_version_34}}",mongodb_sha: "{{mongodb_sha_34}}"}

- get_url:
    url: http://appcenter-docs.qingcloud.com/developer-guide/scripts/app-agent-linux-amd64.tar.gz
    dest: /tmp/app-agent-linux-amd64.tar.gz

- name: Prepare service directories for Mongodb
  file:
    path: "/opt/{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - "app/bin"
    - "mongodb"

- unarchive:
    src: /tmp/{{item.mongodb_version}}.tgz
    dest: /opt/{{ item.mongodb_dir }}
    remote_src: True
    creates: "/opt/{{item.mongodb_dir}}/bin"
    extra_opts: [ '--strip-components=1' ]
  with_items:
  - {mongodb_version: "{{mongodb_version_34}}",mongodb_dir: "mongodb"}


- unarchive:
    src: /tmp/app-agent-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: True
    creates:


- shell: /tmp/app-agent-linux-amd64/install.sh
  become: true
  become_user: root
  args:
    chdir: /tmp/app-agent-linux-amd64/
    creates: /opt/qingcloud/app-agent

- copy: src=limits.conf dest=/etc/security/limits.conf

- copy: src=sysctl.conf dest=/etc/sysctl.conf

- copy: src=mongodb.key dest=/etc/mongodb.key mode=0400 owner=mongodb group=mongodb

- copy: src={{ item }} dest=/opt/app/bin/{{ item }} mode=0777
  with_items:
    - mongo-trib.py
    - restart-mongod-server.sh
    - start-mongod-server.sh
    - stop-mongod-server.sh
    - upgrade.sh

- copy: src={{ item }} dest=/etc/confd/{{ item }}
  with_items:
    - templates/
    - conf.d/

- raw: |
     >~/.bash_history && history -c

